steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/reflex-236915/api', './services/api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/reflex-236915/api']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'api',
        '--image',
        'gcr.io/reflex-236915/api',
        '--region',
        'us-central1',
      ]
images:
  - gcr.io/reflex-236915/api
