const routes = require('next-routes')

export default routes()
  .add('index', '/')
  .add('dashboard', '/dashboard')
  .add('profile', '/profile')
  .add('project', '/projects/:repoOwner/:repoName')
  .add('check', '/checks/:repoOwner/:repoName/:commitSha')
  .add('createOrganization', '/organization')
  .add('organization', '/organizations/:id')
